matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc-5
      env:
        - _CC=gcc-5
        - _CXX=g++-5
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
    - os: osx
      compiler: clang
      sudo: false
language: cpp
before_install:
  - if [ -n "$_CC" ]; then export CC=$_CC; fi
  - if [ -n "$_CXX" ]; then export CXX=$_CXX; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install snappy; fi 
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      # Needed for gcc target and also clang for libstdc++-5-dev
      - gcc-5
      - g++-5
      - libboost-date-time1.55-dev
      - libboost-filesystem1.55-dev
      - libboost-system1.55-dev
      - libsnappy-dev
env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=1
script: mkdir build && cd build && cmake .. && make -j2 && make test
